package com.kheyrinc.hrapi.service;

import com.kheyrinc.hrapi.model.User;
import com.kheyrinc.hrapi.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.Optional;

@Service
public class UserService {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    public User saveUser (User user){
        //String firstname, String lastname, String email, String password
        return userRepository.save(user);
    }


    public Optional<User> getOneUser (final int id){
        return this.userRepository.findById(id);
    }


    public Iterable<User> getAllUser(){
        return this.userRepository.findAll();
    }

    public Optional<User> deleteOneUser(final int id){
        this.userRepository.deleteById(id);
        return null;
    }
}
